- name: install extra packages
  dnf: 
    name: "{{ item }}" 
    state: latest
  with_items:
  - vim-enhanced
    #  - gimp
    #  - gimp-data-extras 
    #  - gimp-lqr-plugin 
    #  - gimp-resynthesizer 
    #  - gimp-paint-studio
  - verne-backgrounds-gnome
  - tmux
  - guake
  - schroedinger-cat-backgrounds-animated
  - schroedinger-cat-backgrounds-gnome
  - gnutls-utils
  - rkhunter
  - gnome-tweak-tool
  - keepass
  - gnome-todo
  - gnome-shell-extension-fedmsg
  - xrdp
  - vinagre
  - gpaste
  - java-openjdk
  - icedtea-web
  - youtube-dl
  - pcsc-tools
  - NetworkManager-openconnect-gnome
  - lshw
- name: start smartcard reader
  service:
    name: pcscd 
    state: started
    enabled: yes
