- name: install extra packages
  dnf: 
    name: "{{ pkg_list_base }}" 
    state: latest

- name: start smartcard reader
  service:
    name: pcscd 
    state: started
    enabled: yes
#sudo dnf copr enable mystro256/gnome-redshift
#sudo dnf install gnome-shell-extension-redshift