- name: install extra packages
  dnf: 
    name: "{{ item }}" 
    state: latest
  loop:
  - vim-enhanced
  - verne-backgrounds-gnome
  - tmux
  - guake
  - schroedinger-cat-backgrounds-animated
  - schroedinger-cat-backgrounds-gnome
  - gnutls-utils
  - rkhunter
  - gnome-tweak-tool
  - keepass
  - gnome-todo
  - vinagre
  - gpaste
  - java-openjdk
  - icedtea-web
  - youtube-dl
 # - pcsc-tools
  - NetworkManager-openconnect-gnome
  - lshw
  - tilix
  - dos2unix
  - libselinux-python
  - rsync
  - deltarpm
  - tlp
  - smartmontools
  - acpi
  - acpid
  - acpitool
  - policycoreutils-python
  - mlocate
  - owncloud-client
#- name: start smartcard reader
#  service:
#    name: pcscd 
#    state: started
#    enabled: yes
#
- name: Enable smartd
  service:
    name: smartd
    state: started
    enabled: yes

- name: Enable trim support
  service:
    name: fstrim.timer
    state: started
    enabled: yes

