- name: install development tools
  dnf: 
    name: "{{ pkg_list_dev }}" 
    state: latest 

- name: Virtualization software
  dnf: 
    name: "{{ pkg_list_virt }}" 
    state: latest

- name: don't auto start libvirtd
  service: 
    name: libvirtd 
    state: stopped 
    enabled: no
