- name: install the rpmfusion repo
  dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Add repository negativo17 - Spotify
  yum_repository:
    description: "negativo17 - Spotify"
    name: fedora-spotify
    baseurl: http://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgkey: http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes
    skip_if_unavailable: yes
    file: fedora-spotify
    enabled: yes

- name: Add repository google-chrome
  yum_repository:
    description: "google-chrome"
    name: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    gpgcheck: yes
    skip_if_unavailable: yes
    file: google-chrome
    enabled: yes
